### ISSUE TITLE
Unable to mount bitlocker encrypted drives (fix included!)

### ISSUE THREAD

**Issue by Subsonic-dev** [feren-OS/Testing-Builds-Bug-Reporting#21]
**Describe the bug**
When mounting a drive encrypted by bitlocker you are unable to mount it after entering the password. The following error is produced:

Error unlocking /dev/sdc: The function 'bd_crypto_bitlk_open' called, but not 
implemented! 

**To Reproduce**
1. Connect bitlocker encrypted drive
2. Open file manager or attempt to mount from tray icon
3. Enter password when prompted
4. Encounter error

**Expected behavior**
Upon entering the password the drive should be decrypted. 

**Screenshots**

**Additional context**
This is different from the issue experienced on foscal ferren and as such there is a simple fix.

`sudo apt install libblockdev-crypto2
systemctl restart udisks2.service`

See similar github issue: https://github.com/pop-os/pop/issues/163

**Comment by Subsonic-dev** [comment]
/home/ferren/Pictures/usb error.png

**Comment by Subsonic-dev** [comment]
Installing the above package libblockdev-crypto2 fixes the issue. To confirm I removed the package and replicated the issue.

**Comment by dominichayesferen** [comment]
Good find! Added to TODO so I remember to add it to feren-meta-drivers.

**Comment by dominichayesferen** [comment]
Fixed in feren-meta-drivers 2023.06.0.0.0 - added recommend
