### ISSUE TITLE
add-apt-repository: Ferenos is not a valid distribution template

### ISSUE THREAD

**Issue by kagirohi** [feren-OS/Testing-Builds-Bug-Reporting#24]
**Describe the bug**
Not able to execute `add-apt-repository`command.
**To Reproduce**
1. To execute add-apt-repository command.
2. To get error message.

**Expected behavior**

**Screenshots**
![Screenshot_20230609_000051](https://github.com/feren-OS/Testing-Builds-Bug-Reporting/assets/57948679/8f0f7f8e-f620-41ae-a4d7-2ddadf80ab38)

**Additional context**
I have installed software-properties-common package.

**Comment by dominichayesferen** [comment]
This is a bug introduced by the changes made for Alpha 2, thus adding the Alpha 2 label as well.

**Comment by dominichayesferen** [comment]
Fixed in the latest `base-files`
