### ISSUE TITLE
feren store

### ISSUE THREAD

**Issue by pablomolano** [feren-OS/Testing-Builds-Bug-Reporting#33]
**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pablomolano** [comment]
no se me ha instalado en el portatil

**Comment by dominichayesferen** [comment]
Store is still in the works, so has not yet been included as it's currently basically unusable for the intended testing context.

I did think it would be ready to drop in Feren OS sooner, thus why I bumped the artwork up to Beta weeks ago, but alas things didn't quite go to plan.

**Comment by pablomolano** [comment]
Aware. Thank you so much.
