### ISSUE TITLE
First login

### ISSUE THREAD

**Issue by ghost** [feren-OS/Testing-Builds-Bug-Reporting#6]
**Describe the bug**
On first login the desktop does not login.

**To Reproduce**
After installation attempt to login.
1. 

**Expected behavior**
Desktop should load and appear normal.

**Screenshots**

**Additional context**
After installatioin the first login always fails. Aftert the first lgoin failure all subsequent logins work normal.
.

**Comment by dominichayesferen** [comment]
Does this still occur on 20.04 Beta 1?

**Comment by ghost** [comment]
Nope. 20.04 Beta 1 is working just fine. For a beta I have no complaints.
