### ISSUE TITLE
"Show tasks of the current Desktop only" is not working (Beta 1)

### ISSUE THREAD

**Issue by lisandrocarmona** [feren-OS/Testing-Builds-Bug-Reporting#7]
All open windows (tasks) are being shown in all Desktops, regardless we set them to be shown in just one.

**Comment by dominichayesferen** [comment]
Changing Icons-Only Task Manager's settings to only show tasks of the current desktop works for me on a fresh installation of 20.04 Beta 1.

**Comment by dominichayesferen** [comment]
I'm gonna assume that since there was no contradiction to that, it's fixed.
