### ISSUE TITLE
Language-packs are kept installing for ever (Beta 1)

### ISSUE THREAD

**Issue by lisandrocarmona** [feren-OS/Testing-Builds-Bug-Reporting#8]
**Describe the bug**
While using system maintenance and installing language-packs, the process hangs and the packages are being prepared for ever (3 hours). 

**To Reproduce**
1. System Maintenance
2. Installing PT language-packs

**Screenshots**
![image](https://user-images.githubusercontent.com/6163906/93348955-412db800-f80d-11ea-98d7-8df483b64d9a.png)

**Comment by dominichayesferen** [comment]
I can't reproduce this on Beta 2 in a 'pt' fresh install, so... guess I'll assume it has fixed itself.
